# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26997f7d9d2ed918b9473be9ad09ecabdbb085d8dce24f39855a67d71d7a057c0f03da07f42e0f30144395c91c85e2c7ab954fe38b17a7dc707d0344daed1e63

test:
  secret_key_base: 59e968e5c78d1d8ab63dbbbf20ea34643e7d0063d47a6492c73743d3e936fe066a13826fd30dc16191a537d14f1251953b7af8446c0552614e4c2d2bc3ecbff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
